### PR TITLE
docs: Create LICENSE 

### PR DESCRIPTION
**Pull request by PreetPatel**
MIT License chosen due to:
1. Its open source loving nature
2. Requires license to be unaltered throughout teams (Version of a license can be changed to suit the altered softwares open or closed source nature)
3. Allows redistribution 
4. Does not make us liable for the software or provide warranty (software provided as is)

Issue #2

### CODE REVIEW

**Comment by Matteas-Eden** [comment]
The MIT license won't enforce the requirement that future developers open-source their software. Are we sure that's okay?

**Comment by jordansimsmith** [comment]
@PreetPatel could you rename the PR to include "closes #2" or similar, its used by the project automation.

**Comment by PreetPatel** [comment]
> @PreetPatel could you rename the PR to include "closes #2" or similar, its used by the project automation.

Done

**Comment by PreetPatel** [comment]
> The MIT license won't enforce the requirement that future developers open-source their software. Are we sure that's okay?
> I'm tempted to suggest the GPL license as an alternative, but it does have its own drawbacks as well, since it's considered more of a headache legally.
> Ultimately, it comes down to whether we're okay with (in our fictitious context) other people taking our code, making a closed source version and selling it.

Will update after discussion with Kelly

**Comment by PreetPatel** [comment]
> For the licenses, we didn’t quite get to covering this in the last lecture, but we will in the next lecture on Monday. I’d suggest your group wait to make a final decision until after next lecture when we discuss the different licenses.
Will update this PR on Monday 9th March

**Comment by jordansimsmith** [comment]
Thanks for the update @PreetPatel. You might want to close the PR if it is not trying to be merged, and reopen it when it is ready to be merged.

**Comment by Matteas-Eden** [comment]
Based on what Kelly has said today, I feel like all we need to do is decide how restrictive we want to be. Obviously there are some limitations given by the course itself (i.e. another group needs to be able to pick up this project), but I think it still comes down to the following questions:
- Are we okay with someone selling our code?
- Does all future work need to be open source?

**Comment by PreetPatel** [comment]
> Based on what Kelly has said today, I feel like all we need to do is decide how restrictive we want to be. Obviously there are some limitations given by the course itself (i.e. another group needs to be able to pick up this project), but I think it still comes down to the following questions:
> 
> * Are we okay with someone selling our code?
> * Does all future work need to be open source?

Open source doesn't mean it always needs to be open-source. It's giving people freedom to do whatever they want on a project built by the community. I reckon Id like to stick to the license that i currently have

**Comment by jordansimsmith** [comment]
With MIT license, are we less or more restricted about the dependencies that we can use? I like the idea of more freedom when it comes to dependencies.

**Comment by PreetPatel** [comment]
> With MIT license, are we less or more restricted about the dependencies that we can use? I like the idea of more freedom when it comes to dependencies.

Agree.. Would like to merge if it looks good to everyone?

**Comment by Matteas-Eden** [comment]
For the slow ones in the back (i.e. myself), could you summarise _exactly_ why we're using MIT over GNU? I'm not convinced that the liability clause @PreetPatel points out in the MIT license is the be all and end all of the discussion. As far as I'm aware, GNU provides a similar limitation of liability while also protecting against closed source versions of our code.

**Comment by PreetPatel** [comment]
> For the slow ones in the back (i.e. myself), could you summarise _exactly_ why we're using MIT over GNU? I'm not convinced that the liability clause @PreetPatel points out in the MIT license is the be all and end all of the discussion. As far as I'm aware, GNU provides a similar limitation of liability while also protecting against closed source versions of our code.

The only difference between GPL and MIT is the restriction by GPL to only opensource future forks that are made. That is it.
Unanimous decision isn't being agreed upon for what we are doing on that regard

**Comment by PreetPatel** [comment]
Organisation poll shows a skewed towards MIT
10 MIT - 8 GPL

**Pull request merged**
