### PR TITLE
Add project description to README closes #8

### LINKED ISSUE #8: Add brief project description to readme
As a software developer I would like to add a brief project description to the readme so that new viewers can understand what the product is.

**Acceptance Criteria**  
- Readme setup with brief project description.

**Notes**  
From the project description:
> brief  project  description  (include  your  team  nameand  a  note  that  this  project  is associated with the University of Auckland SOFTENG 701)

**Blocked by**  
- Selecting a project idea (deadline friday 6 march)

### PR DESCRIPTION
**Pull request by Matteas-Eden**
GitHub Issue (If applicable): #8 

## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## What is the current behavior?

- README lacks project description

## What is the new behavior?

- README contains basic project description

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [x] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by DeshmukhChinmay** [comment]
@Matteas-Eden Looks good. As a side note, would a table with the team members along with the upi be needed in the read me?

**Comment by Matteas-Eden** [comment]
@DeshmukhChinmay We could do that but @salma-s already added a table of that description into the wiki. It also states in the assignment doc that contributors belong in the wiki instead of the README.

@jordansimsmith It's important to maintain consistency imo, so I'll change it if that's what we want to use going forward. I'll also add it to wiki guidelines #26 so we can maintain consistent markdown.

**Comment by DeshmukhChinmay** [comment]
@jordansimsmith I don't think I have write access to the repository so a reviewer with access might be needed to approve to merge this PR automatically.

**Comment by jordansimsmith** [comment]
> @jordansimsmith I don't think I have write access to the repository so a reviewer with access might be needed to approve to merge this PR automatically.

Yep, no worries. Thanks for reviewing, it will be handled from here :)

**Pull request merged**
