### PR TITLE
dark-mode feature toggle

### PR DESCRIPTION
**Pull request by lakshyaoberoi**
GitHub Issue :  #117 

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?

Current behaviour is a simple one-colour standard theme.

## What is the new behavior?

Allows a toggle bar to change from light-mode to dark mode.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by lakshyaoberoi** [comment]
> Looks good 👍 I assume this doesn't change the theming for the modals?

Was working side-by-side with your modals so didn't get a chance to do them. I will do it in the same PR as per @baja156 requests.

**Comment by Sabatr** [comment]
> Hi @lakshyaoberoi ,
> 
> Please do remember to test your code! and fill out the PR template checklist.
> 
> I'm gonna need you to write some unit tests inside of MediaCard.test.jsx (If it doesn't exist, create it!), and also FeedPage.test.jsx accounting for your changes.

I agree with this!

> Hi @lakshyaoberoi ,
> 
> Please do remember to test your code! and fill out the PR template checklist.
> 
> I'm gonna need you to write some unit tests inside of MediaCard.test.jsx (If it doesn't exist, create it!), and also FeedPage.test.jsx accounting for your changes.

I agree with @Kalashnikkov . Unit tests are important!

**Comment by ljcnz** [comment]
LGTM 👍

**Comment by lakshyaoberoi** [comment]
New PR #161

**Pull request closed without merging**
