### PR TITLE
Setup react project closes #15

### LINKED ISSUE #15: Setup base react application
As a developer I would like to setup a base react application to provide a starting point for frontend feature development.

**Acceptance criteria**  
- Project bootstrapped
- Project structure setup
- Test page setup

### PR DESCRIPTION
**Pull request by jordansimsmith**
GitHub Issue (If applicable): #15

## PR Type

What kind of change does this PR introduce?

- Feature
- Build or CI related changes

## What is the current behavior?

- No client project

## What is the new behavior?

- Client project bootstrapped with create-react-app
- `yarn` used as a build tool (recommended by CRA)
- dummy components made to set project structure
- test page created

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [x] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Matteas-Eden** [comment]
Why remove the default `.gitignore`?

**Comment by jordansimsmith** [comment]
> Why remove the default `.gitignore`?

Because we are using the mono repo model, each service has it’s own gitignore. (Avoids a huge global gitignore). The default one is no longer needed

**Comment by Matteas-Eden** [comment]
What did you use to bootstrap it? Your commits don't match what I'd expect from `npx create-react-app <app-name>`, which is what I expected to be used.

**Comment by jordansimsmith** [comment]
> What did you use to bootstrap it? Your commits don't match what I'd expect from `npx create-react-app <app-name>`, which is what I expected to be used.

@Matteas-Eden I used CRA as you mentioned, but did some changes to the files before the first commit. I did think about seeding the initialisation first, but thought it would make for a more complicated history (however would have clarified the question you were asking).

Changes included:
- removed default test files
- removed default CRA landing page
- renamed App.js to App.jsx as it contains JSX
- refactored export statements away from using `export default`
- replaced `function` functions with arrow functions.

**Pull request merged**
