### PR TITLE
Create basic wiki guidelines closes #6

### LINKED ISSUE #6: Define guidelines for wiki
As a software developer I would like to define a set of guidelines for the wiki so that all contributors are agreed on how said wiki should be laid out. This is to ensure documentation that is concise, coherent and readable.  Such documentation also needs to be easy to access and well laid out.

Acceptance Criteria

- Best practices for layout of a (GitHub) wiki researched
- Guidelines for the wiki defined

Notes
https://help.github.com/en/github/building-a-strong-community/about-wikis

### PR DESCRIPTION
**Pull request by Matteas-Eden**
GitHub Issue (If applicable): #6 

## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## What is the current behavior?

- No wiki guidelines exist

## What is the new behavior?

- Wiki guidelines exist

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [x] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Matteas-Eden** [comment]
The guidelines aren't necessarily complete, but I thought it made sense to put up what I had so far. I'm also waiting on a response from Kelly to clarify some things.

**Comment by Matteas-Eden** [comment]
> Single commit so SQUASH label is not relevant here.

At the moment it's only one commit but I expect to add more things/make various edits, so the SQUASH label will likely become more relevant.

**Comment by jordansimsmith** [comment]
> > Single commit so SQUASH label is not relevant here.
> 
> At the moment it's only one commit but I expect to add more things/make various edits, so the SQUASH label will likely become more relevant.

I would suggest only adding the SQUASH label when it is intended to be squashed, not in preparation for future squashing. This would avoid the problem where you add the SQUASH label, commit more individual commits and then it gets squashed when you dont intend it to.

**Comment by Matteas-Eden** [comment]
I got a response from Kelly, so I'll post what she said here and I'll modify the wiki guidelines to reflect it.

> For the list of contributions, it does not need to be very detailed. Just at a high-level. You could, for example, list the features (with a list of associated issues) you implemented and which team members worked on them. You can also list non-technical contributions if needed. I just want to see that everyone on the team did something.

> For the other documentation, again, this should just be what you think is needed for another group to easily take over your project. If the README, contribution guidelines, and code comments are enough, then you might not need anything else here. You will be marked holistically on how well documented the project is (judged by the teaching team and informed by the peer reviews from the group that takes over the project), so if you don’t need any additional documentation here, you won’t lose marks.

**Pull request merged**
